orbs: 
  node: circleci/node@5.0.1

version: 2.1 # using 2.1 provides access to orbs and other features

workflows:
  sample:
    jobs:
      - node/test:
          version: 13.11.0
      - node/test:
          version: 12.16.0
      - node/test:
          version: 10.19.0
