# The deployment section should be excluded until
# it is explicitly included in module 5

#deployment:
 # dockerhub:
  #  branch: master
   # commands:
    #  - $DOCKER_HUB_TRIGGER

version: 2.1

workflows:
  check-build:
    jobs:

test:
  override:    
    - mocha

jobs:
  build-job:
